### ISSUE TITLE
报错，编译不成功

### ISSUE THREAD

**Issue by platform-public** [TuyaInc/tuyasmart_camera_ios_sdk#1]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ALAssetsLibrary", referenced from:
      objc-class-ref in opencv2(cap_ios_video_camera.o)
  "_OBJC_CLASS_$_TuyaSmartCameraConfig", referenced from:
      objc-class-ref in MonitorController.o
  "_OBJC_CLASS_$_TuyaSmartCameraFactory", referenced from:
      objc-class-ref in AppDelegate.o
      objc-class-ref in MonitorController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by platform-public** [comment]
ignoring file 
/Pods/TuyaSmartCamera/TuyaSmartCamera.framework/TuyaSmartCamera, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (arm64): /Pods/TuyaSmartCamera/TuyaSmartCamera.framework/TuyaSmartCamera

**Comment by tuyaLang** [comment]
请参考一下文档中快速集成部分。

**Comment by platform-public** [comment]
是按快速集成步骤来的，原来在gitlab上面pod的没问题，github这个汇报上述错误

**Comment by tuyaLang** [comment]
GitHub 仓库中没有上传SDK，SDK比较大，GitHub中下载会很慢，pod 后面直接跟版本好就行了，README中有写。

**Comment by platform-public** [comment]
Hi，你好，
下面是我podfile和终端截图Xcode报错信息，请帮忙看看什么原因：

**Comment by platform-public** [comment]
改成pod 'TuyaSmartCamera', '3.1.0'就好了，谢谢回复

**Comment by Coderoyal** [comment]
所以，iOS没有个简单的demo吗，必须按照文档手动集成吗，如
   pod 'TuyaSmartCamera'
   pod 'TuyaSmartHomeKit'

这工作量很大啊，每一个API都需要我们去编写，不如提供一个简单的demo

我查看了下Android的，是有完整的demo的(https://github.com/TuyaInc/tuyasmart_camera_android_sdk)
但这个仓库的iOS，不知是不是还没完成，其实不用写那么复杂，有大部分API的调用即可，目前编译报错。如：
.../Example/Pods/TuyaSmartBLEMeshKit/ios/TuyaSmartBLEMeshKit.framework/Headers/TYBleMeshDeviceModel.h:11:13  #import <TYBluetooth/TYBLEPeripheral.h> :   Include of non-modular header inside framework module 'TuyaSmartBLEMeshKit.TYBleMeshDeviceModel': .../Example/Pods/TYBluetooth/TYBluetooth.framework/Headers/TYBLEPeripheral.h

**Comment by tuyaLang** [comment]
这个仓库里的就是demo，pods 目录忽略掉了而已。这个错是因为cocoapods 版本的问题，涂鸦智能公版SDK 暂时还没做好兼容，把cocoapods 降级到 1.5 就好了

**Comment by Coderoyal** [comment]
.../Example/TuyaSmartCamera/Classes/Camera/ViewController/TuyaSmartCameraPlaybackViewController.h:10:9: 'TuyaSmartCameraDefault.h' file not found
#import "TuyaSmartCameraDefault.h"

.../Example/TuyaSmartCamera/Classes/Camera/ViewController/TuyaSmartSDCardViewController.h:10:9: 'TuyaSmartCamera/TuyaSmartCameraDPManager.h' file not found
#import <TuyaSmartCamera/TuyaSmartCameraDPManager.h>

应该是Camera版本没对上吧，找不到这两个头文件。
使用pod 'TuyaSmartCamera'  (默认3.1.1)与pod 'TuyaSmartCamera', '3.1.0' 都不行，麻烦查一下什么原因
