### ISSUE TITLE
pod update 之后会提升一些错误，项目中也会报错

### ISSUE THREAD

**Issue by zoubihai** [TuyaInc/tuyasmart_camera_ios_sdk#10]
![image](https://user-images.githubusercontent.com/19750129/55527684-b6b2d080-56cc-11e9-8494-8917b55fdfed.png)

![Uploading image.png…]()

**Comment by zoubihai** [comment]
![image](https://user-images.githubusercontent.com/19750129/55527707-d649f900-56cc-11e9-98de-5bc226573bf2.png)

**Comment by tuyaLang** [comment]
这是因为涂鸦智能 SDK 打包是用的 cocoaPod 1.5 版本，和 pod 1.6 会有点兼容性问题，暂时只能先把 cocoaPod 降级到 1.5，后面版本会修复这个问题的。

**Comment by zoubihai** [comment]
代码报错也是这个原因吗

**Comment by tuyaLang** [comment]
嗯，编译报错是这个原因。pod update 里的是警告，可以忽略

**Comment by zoubihai** [comment]
![image](https://user-images.githubusercontent.com/19750129/55532288-dbfd0a00-56df-11e9-8d91-b7f01d921e81.png)
现在报这些错误

**Comment by Tuya-Along** [comment]
你可以参照最新 demo 示例代码查看相关用法.device 属性需要自己来进行维护.
