### ISSUE TITLE
CVImageBufferRef imageBuffer = CMSampleBufferGetImageBuffer(sampleBuffer);  获取到的imageBuffer为空

### ISSUE THREAD

**Issue by DoubleFun** [TuyaInc/tuyasmart_camera_ios_sdk#11]
// p2p 2.0 裸流回调
- (void)camera:(id<TuyaSmartCameraType>)camera ty_didReceiveVideoFrame:(CMSampleBufferRef)sampleBuffer frameInfo:(TuyaSmartVideoFrameInfo)frameInfo {
    // 问题1.这种方式转换的  imageBuffer是空的      
    CVImageBufferRef imageBuffer = CMSampleBufferGetImageBuffer(sampleBuffer);
   // 问题2.这里的视频流数据格式是H264还是yuv格式？
   // 问题3: 在这个回调的地方，如何将sampleBuffer对象转换成yuv格式的数据;
}

**Comment by TuyaJim** [comment]
1. 是为NULL，不能直接获取；
2. yuv;
3. sampleBuffer即为解码后的CVImageBufferRef回调对象，可强转CVPixelBufferRef:
CVPixelBufferLockBaseAddress(imageBuffer, 0);
unsigned char *y = (unsigned char *)CVPixelBufferGetBaseAddressOfPlane(imageBuffer, 0);
unsigned char *uv = (unsigned char *)CVPixelBufferGetBaseAddressOfPlane(imageBuffer, 1);
CVPixelBufferUnlockBaseAddress(imageBuffer, 0);

转图片如下：
CVPixelBufferRef pixelBuffer；
CFDictionaryRef attachments = CMCopyDictionaryOfAttachments(kCFAllocatorDefault, pixelBuffer, kCMAttachmentMode_ShouldPropagate);
    CIImage *convertedImage = [[CIImage alloc] initWithCVPixelBuffer:pixelBuffer options:(__bridge NSDictionary *)attachments];
    CFRelease(attachments);
    
    CGImageRef cgimg = [self.videoContext createCGImage:convertedImage fromRect:[convertedImage extent]];
    UIImage *img = [UIImage imageWithCGImage:cgimg];
    CGImageRelease(cgimg);
