### ISSUE TITLE
pod TuyaSmartCameraKit 之後，原本Project的 avcodec_find_decoder(CODEC_ID_PCM_MULAW)失效了

### ISSUE THREAD

**Issue by AllenChang720** [TuyaInc/tuyasmart_camera_ios_sdk#13]
在現有專案pod TuyaSmartCameraKit 之後，
專案用到的 avcodec_find_decoder(CODEC_ID_PCM_MULAW)會return NULL，是否有衝突到？

**Comment by tuyaLang** [comment]
对的，这是 FFmpeg 冲突了，TuyaSmartCameraKit 中使用的 FFmpeg 版本是 3.3.6.

**Comment by AllenChang720** [comment]
請問這樣我就不能使用FFmpeg了嗎？

**Comment by tuyaLang** [comment]
您可以将您项目中的 FFmpeg 升级或者降级到 3.3.6 版本，与 TuyaSmartCameraKit 中的版本保持一致就可以了。
