### ISSUE TITLE
last update with cocoapods

### ISSUE THREAD

**Issue by MimikFc7** [TuyaInc/tuyasmart_camera_ios_sdk#14]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_TYSDKLogUtils", referenced from:
      objc-class-ref in TuyaSmartCameraM(TuyaSmartCameraPpcsImpl.o)
  "_OBJC_CLASS_$_TYSDKDevice", referenced from:
      objc-class-ref in TYCameraCloudServicePanelSDK(TYAppInfoPlugin.o)
      objc-class-ref in TYCameraCloudServicePanelSDK(TYHybridAppPlugin.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by MimikFc7** [comment]
Hello! anybody?

**Comment by tuyaLang** [comment]
what is the version of TuyaSmartCameraKit, TuyaSmartCameraM, TuyaSmartUtil?

**Comment by MimikFc7** [comment]
> what is the version of TuyaSmartCameraKit, TuyaSmartCameraM, TuyaSmartUtil?

Last versions

**Comment by MimikFc7** [comment]
hello? any ideas?

**Comment by tuyaLang** [comment]
Please tell me the specific version of these three frameworks, you can see it from the podfile.

**Comment by MimikFc7** [comment]
> Please tell me the specific version of these three frameworks, you can see it from the podfile.

hello my topic have any information!
i take cocapodf file
add to 
  **pod 'TuyaSmartCameraKit'**
and
  **pod "TuyaSmartHomeKit"**

no more components

and instal 
**pod install** 

and have that error before i delete any pods in my project

**Comment by tuyaLang** [comment]
if you just add pod 'TuyaSmartCameraKit'  and pod "TuyaSmartHomeKit" to your podfile ,there would not have TYCameraCloudServicePanelSDK in your program。you can search 'camera' in the 'podfile.lock' file in root folder，and you can find the version of these frameworks.
