### ISSUE TITLE
想詢問Localplayback檔案的路徑

### ISSUE THREAD

**Issue by AllenChang720** [TuyaInc/tuyasmart_camera_ios_sdk#15]
你好，想詢問localplayback的路徑可以修改嗎，目前都是統一存在手機相簿，這樣我沒辦法知道是哪一隻camera錄的檔案

**Comment by tuyaLang** [comment]
你好，暂时没有提供这样的接口。后续版本有计划会增加指定路径的接口，不过这样的话，就需要开发者自己去实现照片和录像的播放展示。
