### ISSUE TITLE
Push notification implement 問題

### ISSUE THREAD

**Issue by AllenChang720** [TuyaInc/tuyasmart_camera_ios_sdk#17]
你好我想詢問，push notification implement 相關問題，目前我已經.p12檔案上傳，並且在AppDelegate 將token set到TuyaSmartSDK，以及在didFinishLaunchingWithOptions registerForRemoteNotifications．目前實作上述步驟，但是我App收不到push，App端還有需要做什麼設定嗎？

**Comment by tuyaLang** [comment]
push 推送的集成请参考：https://tuyainc.github.io/tuyasmart_home_ios_sdk_doc/zh-hans/resource/Push.html。
