### ISSUE TITLE
Live HD 問題

### ISSUE THREAD

**Issue by AllenChang720** [TuyaInc/tuyasmart_camera_ios_sdk#18]
你好，我目前將demo code的影像移植至我的project，在live開啟HD功能會有鋸齒，可是在demo code 沒有鋸齒，想請問會是哪方面的問題呢？

**Comment by tuyaLang** [comment]
videoView 的 frame 会决定 OpenGL 画布的大小，不要使用 transform 属性去放大 videoView。

**Comment by AllenChang720** [comment]
你好，目前將demo code 檔案複製到我的project，完全使用demo code的UI，還是一樣有鋸齒的問題，想請問會是什麼問題呢？

**Comment by tuyaLang** [comment]
这个内部是使用 OpenGL ES 2.0 在 CAEAGLLayer 上绘制的，画布的大小是根据 CAEAGLLayer 的 bounds 来计算的。可以看看你们项目中有没有什么全局的代码会影响到 OpenGL ES 或者 layer 的bounds。

**Comment by AllenChang720** [comment]
你這邊提到有可能會影響的地方是在 TuyaSmartCamera.m 裡面的這個部分嗎？
- (void)layoutSubviews {
    [super layoutSubviews];
     self.renderView.frame = self.bounds;
}

**Comment by AllenChang720** [comment]
你好我有找到問題了，在我們的專案裡面
[[UIScreen mainScreen] bounds] = (width = 320, height = 568)
在demo code裡面是
[[UIScreen mainScreen] bounds] = (width = 375, height = 667)

我想請問有辦法在不更改為 (width = 375, height = 667) 的情況下，達到沒有鋸齒嗎？

**Comment by tuyaLang** [comment]
[UIScreen mainScreen] 不是手机屏幕大小吗，同样的手机，[[UIScreen mainScreen] bounds] 不一样？

**Comment by AllenChang720** [comment]
同樣的手機(iPhone 6s plus)，好像會因為splash的關係導致尺寸不一樣，目前我們的project沒有放入iPhone 6s plus 相對應尺寸的splash，所以想請問有辦法嗎？

**Comment by tuyaLang** [comment]
这是一个非正常状态吧？这种状态下，我也不知道怎么处理。

**Comment by AllenChang720** [comment]
我使用iPhone 5s 並且放入對應尺寸的splash (Retina 4)，在demo code 上會產生鋸齒問題，想請問你們有辦法解決嗎？

**Comment by tuyaLang** [comment]
暂时没有，猜测是 5s GPU 支持不够。
