### ISSUE TITLE
Module Importing Issue

### ISSUE THREAD

**Issue by rajesh0092** [TuyaInc/tuyasmart_camera_ios_sdk#2]
Hello,
I installed in my Xcode swift project TuyaSmartCamera Library through cocoa pods, After adding the library not able to import the library file in my class it's giving the error that No such module 'TuyaSmartCamera'. Is there any solution for swift to fix the issue.

**Comment by tuyaLang** [comment]
you could add 
#import <TuyaSmartCamera/TuyaSmartCameraFactory.h>
#import <TuyaSmartCamera/TuyaSmartCameraDefines.h>
#import <TuyaSmartCamera/TuyaSmartVideoViewType.h>
in "Your_project_name-Bridging-Header.h".
if there is no such file, you can create any oc file in your project, then Xcode will alert a menu, guide you to create a bridging header.

**Comment by rajesh0092** [comment]
It's fixed.........
But 
request.request(withApiName: "tuya.m.ipc.config.get", postData: [
            "devId": deviceModel.devId
            ], version: "1.0", success: { result in
                print(result!)
        }, failure: { error in
            print(error!)
        })

This api call not giving any response.

**Comment by 0x5e** [comment]
if the `request` instance is a local variable, the network request will be canceled when dealloc. please retain that instance to solve the problem.
See No.2 FAQ: https://tuyainc.github.io/tuyasmart_home_ios_sdk_doc/en/resource/Faq.html
