### ISSUE TITLE
ffmpeg crashes

### ISSUE THREAD

**Issue by dbspark7** [TuyaInc/tuyasmart_camera_ios_sdk#20]
Hello, I am an iOS developer of Truen in Korea.

We have a problem.

When installing the TuyaSmartCameraKit framework, our SDK ffmpeg crashes.

const AVBitStreamFilter *bsf = av_bsf_get_by_name(“h264_mp4toannexb”);

In the above syntax, bsf will be NULL.

Based on Tuya GitHub's other answers, I installed ffmpeg version 3.3.6, but the results are the same.

We pod update and TuyaSmartCameraKit has the latest version installed.

How can we make our ffmpeg load before the TuyaSmartCameraKit ffmpeg installed as a pod?

**Comment by tuyaLang** [comment]
you can update the SDK to : TuyaSmartCameraBase 4.2.5、TuyaSmartCameraM 4.2.5、TuyaSmartCameraKit 4.3.2、TuyaCamera 3.13.3. we use dynamic library in this version , it was solved the conflict problem.
