### ISSUE TITLE
playbackDaysInYear 問題

### ISSUE THREAD

**Issue by AllenChang720** [TuyaInc/tuyasmart_camera_ios_sdk#22]
你好想詢問關於此function的應用
- (void)playbackDaysInYear:(NSInteger)year month:(NSInteger)month complete:(void (^)(TYNumberArray *))complete 
目前使用起來有遇到一個問題，假設我要抓最近六個月檔案我會call六次，但是每次都要重新connectCamera才能抓到檔案，沒辦法使用同一個connect去抓六次

**Comment by tuyaLang** [comment]
不用重新connectCamera，connect 成功后，可以多次调用这个方法。

**Comment by AllenChang720** [comment]
你好，因為我需要一次抓取最近的六個月檔案，但是我在調用
- (void)playbackDaysInYear:(NSInteger)year month:(NSInteger)month complete:(void (^)(TYNumberArray *))complete 
這個function後，再次調用此function我會收到以下
Error TYCameraSDK [ERROR]: don't invoke sdk function in sdk callback(may cause deadlock).
