### ISSUE TITLE
Live sampleBuffer 問題

### ISSUE THREAD

**Issue by AllenChang720** [TuyaInc/tuyasmart_camera_ios_sdk#23]
我從底下function 取得 sampleBuffer
- (void)camera:(TuyaSmartCamera *)camera didReceiveVideoFrame:(CMSampleBufferRef)sampleBuffer frameInfo:(TuyaSmartVideoFrameInfo)frameInfo

想將sampleBuffer轉換成UIImage，但是CMSampleBufferGetImageBuffer(sampleBuffer)會回傳NULL，想請問是為什麼呢？

**Comment by tuyaLang** [comment]
CVPixelBufferRef pixcelBuffer = (CVPixelBufferRef)sampleBuffer;  然后使用 pixcelBuffer 去转换。
