### ISSUE TITLE
门铃相关SDK问题

### ISSUE THREAD

**Issue by ZYFxy7816** [TuyaInc/tuyasmart_camera_ios_sdk#25]
有人按 peephole 的門玲, 手机APP如果在前端, 會出现预览画面和push notification, 否则就只有push notification

但是我们拿tuya SDK开发的app，無法在有人按peephole 門玲時 trigger push notification 或令手機APP 产生预览画面; 我们在IPC sdk里面没找到
 我想問的是此SDK能否提供一下。

**Comment by tuyaLang** [comment]
新的文档里已经有添加这部分的介绍，参考低功耗门铃章节。
