### ISSUE TITLE
Pod update後專案錯誤

### ISSUE THREAD

**Issue by AllenChang720** [TuyaInc/tuyasmart_camera_ios_sdk#26]
你好，為什麼我pod update完之後，我的專案會顯示以下錯誤

![截圖 2020-02-27 17 34 12](https://user-images.githubusercontent.com/34335572/75431240-8977ac80-5987-11ea-8a22-8dfff13d4637.png)

**Comment by tuyaLang** [comment]
你好，请问你接入的 TYCameraCloudServicePanelSDK  是什么版本？可以在 podfile.lock 里查看一下。

**Comment by AllenChang720** [comment]
是   - TYCameraCloudServicePanelSDK (0.1.0) ，請問該如何解決呢？

**Comment by tuyaLang** [comment]
需要在你的 podfile 文件顶部添加这个：source 'https://github.com/TuyaInc/TYPublicSpecs.git'，这是涂鸦的公开库源。最新的文档：https://tuyainc.github.io/tuyasmart_camera_ios_sdk_doc/zh-hans/resource/cloud_video.html
