### ISSUE TITLE
ffmpeg conflict

### ISSUE THREAD

**Issue by AllenChang720** [TuyaInc/tuyasmart_camera_ios_sdk#27]
我的專案裡面也有用到ffmpeg，在pod install 

  pod 'TuyaSmartHomeKit'
  pod 'TuyaSmartCameraKit'
  pod 'TYCameraCloudServicePanelSDK'

完之後，我在avcodec_find_decoder(CODEC_ID_PCM_MULAW) 會return NULL ，請問有什麼方法解決嗎？

**Comment by tuyaLang** [comment]
你需要将你使用的 ffmpeg 打包成动态库。
