### ISSUE TITLE
What is setupWithAppScheme: ? What we need to update data in <#Your Scheme#>?

### ISSUE THREAD

**Issue by Lyankar** [TuyaInc/tuyasmart_camera_ios_sdk#29]
[TYCameraCloudServicePanelSDK setupWithAppScheme:<#Your Scheme#>];

**Comment by lal603743923** [comment]
![image](https://user-images.githubusercontent.com/17883682/78352233-987ef980-75da-11ea-8a8b-0df19332e577.png)
this scheme is the channel ID that you register in the Tuya development platform .
you can register refer to this Documentation: https://tuyainc.github.io/tuyasmart_home_ios_sdk_doc/en/resource/Preparation.html
