### ISSUE TITLE
截图、录像、对讲等功能是否依赖 - (UIView<TuyaSmartVideoViewType> *)videoView;

### ISSUE THREAD

**Issue by TenJunky** [TuyaInc/tuyasmart_camera_ios_sdk#3]
如果我们app端视频播放器，用自己写的，那哪些截图、录像、对讲功能是否也需要我们自己实现，还是调用你们原来的接口就可以？

**Comment by tuyaLang** [comment]
这些不依赖videoView，但是SDK没有提供解码后的图像数据。如果要自己实现播放器，那么就得走裸流接口，这样，SDK内部不会对视频数据做解码操作，需要你们自己解码，截图，录像也就需要你们自己实现了。而且目前 p2p 2.0 的摄像头暂未提供裸流接口，只有 p2p 1.0 的有提供。

**Comment by TenJunky** [comment]
非常感谢你们的解答

**Comment by TenJunky** [comment]
如何确定走的是p2p 1.0 还是2.0？

**Comment by tuyaLang** [comment]
从deviceModel.skills 中获取，也就是创建摄像头时传入的 p2pType，1 就是 1.0， 2 就是 2.0，这个是设备固件的版本决定的。
