### ISSUE TITLE
I'm unable to add Camera SDK in my app. I got these errors. 

### ISSUE THREAD

**Issue by Lyankar** [TuyaInc/tuyasmart_camera_ios_sdk#30]
[!] Unable to read the license file `LICENSE` for the spec `TuyaCameraSDK (3.15.4)`

[!] Unable to read the license file `LICENSE` for the spec `TuyaSmartCameraBase (4.4.3)`

[!] Unable to read the license file `LICENSE` for the spec `TuyaSmartCameraKit (4.4.4)`
...
...

My pod file is: 

pod "TuyaSmartHomeKit"

  pod 'TuyaSmartBLEKit'
  pod 'TuyaSmartBLEMeshKit'
  pod 'TuyaSmartFeedbackKit'
  pod 'TuyaSmartMessageKit'
  pod 'TuyaSmartSceneKit'
  pod 'TuyaSmartTimerKit'

pod "TuyaSmartActivatorKit"
  pod 'TuyaSmartCameraKit'

**Comment by tuyaLang** [comment]
these is warnings, please ignore these.
