### ISSUE TITLE
ffmpeg cannot init  AVFormatContext with output FLV filename.

### ISSUE THREAD

**Issue by lucas0-coder** [TuyaInc/tuyasmart_camera_ios_sdk#40]
- If NOT TUYA SDK integrated, App can init AVFormatContext (with FLV output) ok.
But with TUYA SDK integrated, APP can only init AVFormatContext with MP4 filename ok.
When init AVFormatContext with FLV, it return error-code -22 (see Demo Project & attached log file fore more detail)

Demo project plz see link: https://www.dropbox.com/s/umaysjkztnydiom/VideoEncode_x264-master-shared.zip?dl=0

**Comment by tuyaLang** [comment]
It must be the FFmpeg you use is not compatible with our SDK. You can package your FFmpeg modules into a dynamic library to solve this problem.

**Comment by lucas0-coder** [comment]
Can you more specific the answer? Cause the FFMpeg compile for iOS is already a static library. How can we change it to dynamic?

**Comment by tuyaLang** [comment]
You need to compile the entire business module which using FFMpeg into a dynamic framework，if your already use a framework, please check if the Mach-O type of your framework is dynamic library.

**Comment by lucas0-coder** [comment]
Hi, Can you verify the answer before tell us what to do.
We already compiled the entire FFMpeg into a dynamic framework, but the issue is still the same.
While this solution not work, can you help to check again,
Many Thanks.
![Screen Shot 2021-04-27 at 5 09 26 PM](https://user-images.githubusercontent.com/83009463/116225843-7f646000-a77c-11eb-9b57-026cf4660235.png)

**Comment by lucas0-coder** [comment]
Many thanks for support. It's working now, the dynamic framework solution is perfect.
Thanks a lot.

**Comment by lucas0-coder** [comment]
working now
