### ISSUE TITLE
摄像头和机器人一次配网问题

### ISSUE THREAD

**Issue by T2015** [TuyaInc/tuyasmart_camera_ios_sdk#7]
可以配网成功，也可以拿到设备信息，但是视频无法播放，走回调- (void)camera:(id<TuyaSmartCameraType>)camera didOccurredError:(TYCameraErrorCode)errCode
错误信息：TY_ERROR_START_PREVIEW_FAILED

注：
一直打印信息：
2019-03-19 17:08:17.904990+0800 LS[1770:364085]  --- 2.200000
2019-03-19 17:08:17.933237+0800 LS[1770:364085]  --- 2.200000

**Comment by tuyaLang** [comment]
p2p 连接成功了吗？就是 cameraDidConnected: 有回调没？

**Comment by T2015** [comment]
- (void)cameraDidConnected:(id<TuyaSmartCameraType>)camera{
    
    NSLog(@"cameraDidConnected");
    
    // 回放通道
//    [self.camera enterPlayback];
//    [MBProgressHUD hideAnimation:YES inView:self.view];
    [self.camera startPreview];
}
这个回调了

**Comment by T2015** [comment]
设备id ：6c11f37afed7ef44a4qelx

**Comment by tuyaLang** [comment]
可以把涂鸦平台的 appkey ,appsecret，以及测试账号密码发给我一下吗，可以发到我的邮箱：fulang@tuya.com，我这边好查一下具体的问题。

**Comment by T2015** [comment]
已发

**Comment by tuyaLang** [comment]
好的，谢谢

**Comment by tuyaLang** [comment]
你好，我这边查到p2p连接成功后，开启预览一直没有视频流传过来，导致超时了。建议将设备换一个网络重新配网再看看。

**Comment by T2015** [comment]
嗯，测试完给你反馈

**Comment by T2015** [comment]
数据已通，可能是嵌入式那边的问题
